fragment GalleryParts on Gallery {
  __typename
  photos {
    __typename
    image
    caption
  }
}

fragment PressParts on Press {
  __typename
  clippings {
    __typename
    image
    title
    date
    link
  }
}
